/* eslint-disable no-mixed-spaces-and-tabs */
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: "300px",
      xsm: "425px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
      "3xl": "1920px",
    },

    fontFamily: {
      sans: ["var(--font-nunito)", "sans-serif"],
      fredoka: "Fredoka One",
      Nunito: ["var(--font-nunito)", "sans-serif"],
      rubik: ["Rubik", "sans-serif"],
      mukta: ["Mukta", "sans-serif"],
      jakara: ["var(--font-plus-jakarta)", "sans-serif"],
      lato: ["var(--font-lato)", "sans-serif"],
    },
    extend: {
      animation: {
        "bounce-200": "bounce 1s infinite 200ms",
        "bounce-400": "bounce 1s infinite 400ms",
      },
      colors: {
        brand: {
          dark: "#414042",
          accent: {
            DEFAULT: "#9bba70",
            light: "#d0d8ba",
          },
          darkgray: "#4d4d4d",
          lightgrey: "#e6e7e8",
          lightGreen: "#a5c174",
          disgray: "#9ca3af",
          error: "#e7aa68",
        },
        textWhite: {
          white: "#ffffff",
        },
        "custom-yellow": "#a5c174",
        "custom-green": "#b7d340",
        "custom-gray": "#414042",
        "custom-black": "#3e3e3e",
        "custom-light-gray": "#414042",
        "custom-blue": "#eaf4f1",
        "custom-lightGray": "#C1C1C1",
        "custom-lightGreen": "#C4DA62",
        "custom-lightBlack": "#414042",
        "custom-blueshade1": "#68aa9e",
        "custom-lightgrey": "#F8F8F8",
        "custom-verylightgreen": "#CDE07A",
        "custom-bordergrey": "#C8D0CE",
        "custom-borderdarkgrey": "#D9D7D7",
        "custom-light": "#F1F1F1",
        "custom-fontgrey": "#73767d",
        "custom-grey": "#e6e7eb",
        "custom-bordercolor": "#ebf1e2",
        "custom-headergrey": "#9ca3ad",
        "custom-orange": "#F2E5A5",
        "custom-pink": "#F7D0A6",
        "custom-lightpink": "#F7E0D0",
        "custom-newverylightgreen": "#F0F9FF",
        "custom-boxgreen": "#E0F0C8",
        "custom-newpink": "#F7CFB5",
        "custom-neworange": "#FFF3C9",
        "custom-fontorange": "#F2B46A",
        "custom-rootCauseBg": "#F7F7F7",
        "custom-rootCauseBgMobile": "#EAF4F1",
        "custom-footerpink": "#FFB7A1",
        "custom-logingrey": "#F4F8EF",
        "custom-loginbordergreen": "#96CF8D",
        "custom-logintextgrey": "#7C7D7A",
        "custom-loginheadergreen": "#B6D748",
        "custom-border-login": "#96CF8D",
        "custom-border-blue": "#40D3B9",
        "custom-disable-grey": "#D0CFCF",
        "custom-light-grey": "#B0B0B0",
        "Text/Heading-Text": "#171819",
        "Text/Body-Text": "#313233",
        "Elements/Divider-Stroke": "#E3E3E2",
        "Neutral/900": "#171819",
        "Background/AirBlue": "#DCEBF2",
        "Primary/500": "#2872A1",
        "Background/Beige": "#F9F7F2",
        "Primary/900": "#081720",
        "Neutral/100": "#E5E5E5",
        "Text/Label": "#4B4B4C",
        "Primary/50": "#D9E6EF",
        "Neutral/400": "#989899",
        "Background/Aqua": "#D2E5E1",
        "Neutral/200": "#CCCCCC",
        "Primary/100": "#B6CFDF",
        "custom-border-Primary/100": "#8CC5FA",
        "custom-text-loader-small": "#505354",
        "custom-text-loader-header": "#141515",
        "custom-text-loader-subText": "#313233",
        "Semantic/Error": "#B3261E",
        "Semantic/ErrorLight": "#FBEEED",
        "Neutral/700": "#505354",
        "Neutral/600": "#505354",
        "Neutral/800": "#141515",
        Accent: "#BED9C7",
        "Semantic/Success": "#19785D",
        "Tertiary/600": "#0A344F",
        "Tertiary/400": "#237AB1",
        "Tertiary/700": "#021523",
        "Elements/Highlight": "#F4F4F4",
        "Text/Disabled": "#969B9D",
        "Overlay Popup/Divider Stroke": "#DDDDDD",
        "Elements/Divider Stroke": "#E3E3E2",
        "Secondary/50": "#FEFDFC",
        "Secondary/400": "#AFA792",
        "text-icon/title": "#2C2C2A",
        "surface/disabled-state": "#F3F3F2",
        "text-icon/subtitle": "#5E5E5A",
        "text-icon/label-tertiary": "#787872",
        "text-icon/body": "#40413E",
        "Radial/Gradient": "#000000",
        "primary/700": "#0E1518",
        "color/cyan/6": "#041C1B",
        "Tertiary/500": "#16567E",
        "Grey-Neutral/400": "#727678",
        ProductAddNow: "#FFC942",
        "Tertiary/200": "#8CC5FA",
      },
      fontSize: {
        xxs: "0.6rem",
        xx4l: "44px",
        x4l: "40px",
        x2l: "27px",
        x1s: "16px",
      },
      height: {
        84: "19.0rem",
        85: "22rem",
        400: "25rem",
      },
      screens: {
        landscape: { raw: "(max-height: 640px)" },
      },
      lineHeight: {
        3: "0.75rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
      },
      backgroundColor: {
        "custom-bg-overlay":
          "linear-gradient(180deg, rgba(0, 0, 0, 0.315) 74.39%, rgba(0, 0, 0, 0.7) 95.58%)",
      },
      backgroundImage: {
        "aqua-gradient-border":
          "linear-gradient(90deg, #F9F7F2 0%, #BED9C7 21.31%, #BED9C7 81.11%, #F9F7F2 100%)",
      },
      boxShadow: {
        "custom-top": "0px -4px 32px 0px rgba(0, 0, 0, 0.25)",
        "custom-small": "0px -1px 4px 0px rgba(0, 0, 0, 0.25)",
        "custom-medium": "0px -2px 12px 0px rgba(0, 0, 0, 0.15)",
      },
    },
  },
  variants: {
    backgroundColor: ({ after }: any) => after(["disabled"]),
    textColor: ({ after }: any) => after(["disabled"]),
    cursor: ({ after }: any) => after(["disabled"]),
  },
};

export default config;
