export const ADD_PREVIOUS_QUESTIONS = "ADD_PREVIOUS_QUESTIONS";
export const CHANGE_CURRENT_QUESTION = "CHANGE_CURRENT_QUESTION";
export const INITIALIZE_STATE = "INITIALIZE_STATE";
export const MAKE_QUESTIONS_LIST = "MAKE_QUESTIONS_LIST";
export const NEXT_QUESTION = "NEXT_QUESTION";
export const REMOVE_PREVIOUS_QUESTIONS = "REMOVE_PREVIOUS_QUESTIONS";
export const SAVE_API_RESPONSE = "SAVE_API_RESPONSE";
export const SAVE_QUESTION_REPLY = "SAVE_QUESTION_REPLY";
export const SAVE_GENDER_REPLY = "SAVE_GENDER_REPLY";
export const SAVE_SLOTS = "SAVE_SLOTS";
export const SAVE_SLOTS_LIST = "SAVE_SLOTS_LIST";
export const SET_PREVIEW_URL = "SET_PREVIEW_URL";
export const SET_FORM_ALL_QUESTIONS_FILLED = "SET_FORM_ALL_QUESTIONS_FILLED";
export const SAVE_QUESTIONS_OTHER_ATTRIBUTES =
  "SAVE_QUESTIONS_OTHER_ATTRIBUTES";
export const SET_FORM_IS_MALE = "SET_FORM_IS_MALE";
export const CHANGE_QUESTION_LANGUAGE = "CHANGE_QUESTION_LANGUAGE";
export const SET_USER_AGE = "SET_USER_AGE";
export const SAVE_USER_FORM_RESPONSES = "SAVE_USER_FORM_RESPONSES";

export const RESET_STATE = "RESET_STATE";
export const SET_HAUT_AI_RESPONSE = "SET_HAUT_AI_RESPONSE";
