import React from "react";
import rightArrow from "@assets/svg/rightArrow.svg";
import Image from "next/image";

const TermsConditionsPage = () => {
  return (
    <div className="flex lg:justify-center">
      <div className="px-4 pb-14 lg:w-[65%] lg:px-0 mt-20">
        <div className="flex items-center gap-x-1 mb-8">
          <a href="/" className="font-lato text-xs text-gray-700">
            HOME
          </a>
          <Image src={rightArrow} alt="logo" width={12} height={12} />
          <a
            href="/terms-conditions"
            className="font-lato text-xs text-gray-700"
          >
            TERMS OF SERVICE
          </a>
        </div>
        <h2 className="font-lato font-bold xs:text-[30px] md:text-[50px] text-left leading-[44px] mb-1 lg:leading-[60px]">
          TERMS OF SERVICE
        </h2>
        <div className="font-lato text-[17px]">
          <p>
            This document is an electronic record in terms of Information
            Technology Act, 2000 and rules thereunder, as applicable and the
            amended provisions pertaining to electronic records in various
            statutes, as amended from time to time by the Information Technology
            Act, 2000. This electronic record is generated by a computer system
            and does not require any physical or digital signatures.
          </p>
          <br />
          <br />
          <div className="flex">
            <strong className="pr-4">1.</strong>
            <p className="font-bold">INTRODUCTION</p> <br />
            <br />
          </div>
          <div className="flex pl-4">
            <span className="pr-4">(a).</span>{" "}
            <p>
              These terms of service (“Terms”) govern the use of or access to an
              internal based portal available at clear.rituals  on a
              computer device or a mobile device (“Website”), the mobile
              application (“App”), and the Products and Services (defined
              below). The Website and App are collectively referred to as the
              “Platform”.{" "}
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>{" "}
            <p>
              These Terms include any rules, guidelines, policies, additional
              terms, or disclaimers made available or issued by us from time to
              time and such rules, guidelines, policies, additional terms, or
              disclaimers shall be deemed to be incorporated into, and
              considered as part and parcel of these Terms.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(c).</span>{" "}
            <p>
            (c)	These Terms constitute a binding and enforceable legal contract between Tatvartha Health Private Limited, with its registered address at C-7, 67/P, Fortune Hotel Galaxy, N. H. No 8, Koparli Road, GIDC NA, Vapi, Valsad – 396195, Gujarat (“MoolHealth”, “we”, “us”, or “our”) and you, an end-user of our Products or Services (“you”). You represent and warrant that you (i) have full legal capacity and authority to agree and bind yourself to these Terms, and (ii) are of the age of majority or older in accordance with Indian law.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(d).</span>{" "}
            <p>
              By browsing, accessing or using the Platform or using/availing the
              Services or purchasing the Products, you agree that you have read,
              understood, and are bound by these Terms, and that you comply with
              the requirements listed herein. If you do not agree to all or any
              of these Terms or comply with the requirements herein, please do
              not access or use the Platform, purchase the Products, or use the
              Services. Use of the Platform is offered to you, subject to
              acceptance of all the terms, conditions and notices contained in
              these Terms including applicable policies which are incorporated
              herein by reference, along with any amendments / modifications
              made time to time by us at our sole discretion and posted on the
              Platform, including by way of imposing an additional charge for
              access to or use of a service(s).
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(e).</span>{" "}
            <p>
              The Platform is operated, and Services and Products are offered in
              compliance with the laws in India. If you access our Services from
              locations outside India, you do so at your own risk and you are
              solely liable for compliance with applicable local laws. We make
              no representation that the content on the Platform is appropriate
              to be used or accessed outside the Republic of India. Any user who
              uses or accesses the Platform from outside the Republic of India,
              do so at their own risk and are responsible for compliance with
              the laws of such jurisdiction. These Terms do not constitute, nor
              may these Terms be used for or in connection with any promotional
              activities or solicitation by anyone in any jurisdiction in which
              such promotional activities or solicitation are not authorized or
              to any person to whom it is unlawful to promote or solicit. Where
              you use any third-party website or the products or services of any
              third party, you may be subject to alternative or additional terms
              and conditions of use and privacy policies.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(f).</span>{" "}
            <p>
              We reserve the right to change or modify these Terms or any policy
              or guideline of the Platform including the Privacy Policy, at any
              time and in our sole discretion. Any changes or modifications will
              be effective immediately upon posting the revisions on the
              Platform and you waive any right you may have to receive specific
              notice of such changes or modifications, provided however that, we
              will inform you of such changes within such timelines as may be
              specified under the applicable laws. Your continued use of the
              Platform or Services will confirm your acceptance of such changes
              or modifications; therefore, you should frequently review these
              Terms and applicable policies to understand the terms and
              conditions that apply to your use of the Platform or the Services.
            </p>
          </div>
          <br />
          <br />
          <div className="flex">
            <strong className="pr-4">2.</strong>
            <p className="font-bold">OUR SERVICES AND PRODUCTS</p> <br />
            <br />
          </div>
          <div className="flex pl-4">
            <span className="pr-4">(a).</span>{" "}
            <p>
              Services: The Platform allows you to access and purchase the
              Products, connect with our representatives through chat features
              or calls, undertake paid consultations with healthcare
              professionals, undertake and obtain gut health assessments,
              receive diagnoses/feedback, get access to certain healthcare
              professionals prescribed Products, get Product recommendations,
              avail customized plans, receive free trials of the Platform, track
              your progress, and any other services as may be made available by
              us on the Platform from time to time (all the services described
              here, including the provision of the Platform and its features,
              collectively constitute the “Services”).
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>{" "}
            <p>
              Products: The Platform facilitates online purchase of a wide range
              of gut health related products ayurvedic medicines etc.
              (“Products”) sold by Us from our licensed premises. The Products
              may be eligible for returns or exchanges in accordance with our
              policies.{" "}
            </p>
          </div>
          <br />
          <p className="pl-4">
            <span className="pr-4">(c)</span>Sale of Products –
          </p>
          <ul className="list-disc pl-16">
            <li>
              Listing and displaying a Product by us on the Platform is our
              invitation to you to make an offer for purchase of such Product.
              Likewise, the placement of an order on the Platform by you is your
              offer to buy the Product(s) from us.
            </li>
            <li>
              Once you have placed an order with us for purchase of a Product,
              you will receive an e-mail and/or mobile confirming receipt of
              your order and containing the details of your order (the “Order
              Confirmation”). The Order Confirmation is merely an
              acknowledgement that we have received your order and does not
              signify our acceptance of your offer.
            </li>
            <li>
              We only accept your offer and conclude the contract of sale for
              Products ordered by you, when the Product is shipped or dispatched
              to you and an e-mail confirmation and/or confirmation to your
              registered mobile number is sent stating that the Product has been
              shipped or dispatched (the “Shipment Confirmation”). We reserve
              the right, at our sole discretion, to refuse or cancel any order
              for any reason whatsoever before sending Shipment Confirmation to
              you.
            </li>
            <li>
              If your order is dispatched in more than one package, you may
              receive separate Shipment Confirmations for each package, and each
              Shipment Confirmation and corresponding dispatch will conclude a
              separate contract of sale between you and us for the Product(s)
              specified in that Shipment Confirmation.
            </li>
            <li>
              Any communication from us shall be sent only to your registered
              mobile number and/or email address or such other contact number or
              email address that you may designate, for any particular
              transaction. You shall be solely responsible to update your
              registered mobile number and/or email address on the Platform in
              the event there is a change. Further, we may also send you
              notifications and reminders with respect to scheduled deliveries
              of the purchased Products. While we shall make every endeavour to
              share prompt reminders and notifications relating to the delivery
              of purchased Product(s) with you, we shall not be held liable for
              any failure to send such notifications or reminders to you.
            </li>
            <li>
              All orders placed on the Platform are subject to the availability
              of such Products, our acceptance of your offer as per the above
              and your continued adherence to these Terms and other conditions
              as may be specified under applicable law.
            </li>
            <li>
              You hereby authorise us to declare and provide declarations to any
              governmental authority on request on your behalf, including that
              the Products ordered by you are for personal, non-commercial use.
            </li>
          </ul>
          <br />
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(d).</span>{" "}
            <p>
              Completion of Sale: Upon acceptance of the offer by us, the
              Products would be dispensed in accordance with the terms of the
              order placed by you. You agree and acknowledge that the property
              and title in the Products ordered by you shall stand immediately
              transferred to you upon the dispensation of Products. Accordingly,
              the sale of Products is concluded at the concerned warehouse
              itself. The invoice in relation to the Products, that are required
              to be delivered to you shall be issued by us.
            </p>
          </div>
          <br />
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(e).</span>
            <p>
              Purchase and Shipment of Products: We reserve the right to refuse
              any order for Products you place with us. We may, in our sole
              discretion, limit or cancel quantities purchased per person, per
              household or per order. These restrictions may include orders
              placed by or under the same customer account, the same credit
              card, or orders that use the same billing or shipping address. In
              the event that we make a change to or cancel an order, we may
              attempt to notify you by contacting the e-mail address, billing
              address, or phone number provided at the time the order was made.
              We reserve the right to limit or prohibit orders that, in our sole
              judgment, appear to be placed by dealers, resellers or
              distributors. All Products shall be prepared for shipment in a
              manner that is adequate to ensure safe dispatch and arrival.
              Please note that there may be delays in delivery due to reasons
              beyond our control as detailed in Section 9(k). We will not be
              responsible for delays in delivery due to reasons beyond our
              control. You will receive all notifications by e-mail and SMS
              regarding the order details and the probable dispatch date.
            </p>
          </div>
          <br />
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(f).</span>
            <p>
              Products Delivery: The Products shall be delivered by us or
              independent contractors. You accept and acknowledge that the
              courier/ delivery personnel, engaged by us, shall be your agent
              for the delivery of the Products to the address notified by you,
              with no control over the Products and no additional obligation
              apart from standard delivery obligations and duty of care. You
              further agree and acknowledge that such courier/ delivery
              personnel acts as your agent. The services are being undertaken by
              your agent with your consent and therefore we are merely
              facilitating this and will have no liability or responsibility in
              this regard.
            </p>
          </div>
          <br />
          <br />
          <div className="pl-4 flex">
            <span className="pr-4">(g).</span>
            <p>Terms for Availing Customized Plan</p>
          </div>
          <br />
          <ul className="list-disc pl-16">
            <li>
              MoolHealth provides an online portal to the users for availing gut
              wellness solutions and services by facilitating a customized gut
              health plan for the users from healthcare professionals and
              experts pursuant to certain Information, consultation and further
              diagnosis (“Customized Plan”){" "}
            </li>
            <li>
              The users who intend to avail themselves of a Customized Plan have
              to answer a few queries and provide information on the Platform
              (“Information”). The users have to answer a series of questions
              consisting of health-related information. The users may also be
              required to provide additional information such as images, food
              habits, diagnostic test reports, family medical history etc.
              depending on a case-to-case basis. The user understands and agrees
              that the user has to provide accurate, correct, true and
              up-to-date Information.{" "}
            </li>
            <li>
              Based on a review of the Information, the users are suggested a
              Customized Plan. Once the user confirms, we proceed to get the
              payments in relation to the Customized Plan. Please note that the
              delivery of the Products further to Customized Plan is contingent
              on the review and approval of your Customized Plan by a healthcare
              professional as may be applicable. As stated above, the contract
              of sale will get complete only when the Products are shipped or
              dispatched to you and an e-mail confirmation and/or confirmation
              to your registered mobile number is sent stating that the Product
              has been shipped or dispatched.{" "}
            </li>
            <li>
              The Customized Plan shall contain instructions for the user to
              follow along with the Products that are to be consumed by the
              user, the dietary and lifestyle habits that the user will have to
              follow etc. After the delivery of your Customized Plan, a
              representative may also reach out to you to help you understand
              the Customized Plan, guide you on how to take the Products and any
              other instructions that you may have to follow during your course.
            </li>
          </ul>
          <br />
          <div className="flex">
            <strong className="pr-4">3.</strong>
            <p className="font-bold">ELIGIBILITY OF USE</p> <br />
            <br />
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(a).</span>
            <p>
              Use of the Platform is available only to persons who can form
              legally binding contracts under Indian Contract Act, 1872. Persons
              who are incompetent to contract within the meaning of the Indian
              Contract Act, 1872 including without limitation, minors,
              un-discharged insolvents etc. are not eligible to use the
              Platform. The Products shall also not be available to any users
              suspended or removed from our system for any reason whatsoever. If
              you do not conform to the above qualification, you will not be
              permitted to put a requisition for the Products or the Services
              through the Platform.
            </p>
          </div>
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>
            <p>
              By accessing and using the Platform or availing the Services, you
              represent that you are an Indian national, located in India, are
              of legal age to form a binding contract and are not a person
              barred from entering into a contract under the laws as applicable
              in India. Notwithstanding the foregoing, if you are below the age
              of eighteen (18) years, you may avail the Services, through your
              legal guardian in accordance with the applicable laws. We reserve
              the right to cancel your account and / or refuse to provide you
              with access to the Platform if it is brought to our notice or if
              it is discovered that you are under the age of 18 years. We
              reserve the right to refuse access to use the Services to new
              users or to terminate access granted to existing users at any time
              without according any reasons for doing so and you shall have no
              right to object to the same.
            </p>
          </div>
          <div className="flex pl-4">
            <span className="pr-4">(c).</span>
            <p>
              You shall not have more than one active Account (defined below).
              Additionally, you are prohibited from selling, trading, or
              otherwise transferring Your Account to another party.
            </p>
          </div>
          <br />
          <div className="flex ">
            <strong className="pr-4">4.</strong>
            <p className="font-bold">ACCOUNT CREATION</p>
            <br />
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(a).</span>
            <p>
              To use certain features of the Platform or avail the Services or
              purchase the Products you will have to register with us and create
              an account (“Account”).{" "}
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>
            <p>
              You are solely responsible for (i) maintaining the confidentiality
              of your Account and password and for restricting access to your
              device; (ii) for all activities that occur under your Account or
              password. You agree to immediately notify us of any disclosure or
              unauthorised use of your Account or any other breach of security;
              (iii) non-compliance with applicable laws, rules, regulations and
              guidelines as may be notified from time to time and (iv) ensure
              that you exit / log out from your Account at the end of each
              session. We are not liable for any loss or damages that may arise
              from your failure to ensure the confidentiality of your account or
              password.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(c).</span>
            <p>
              You warrant that all information furnished in connection with your
              Account is and shall remain complete, up to date, accurate and
              true in all respect and agrees that you shall promptly update your
              details on the Platform in the event of any change or
              modification.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(d).</span>
            <p>
              You will be responsible for maintaining the confidentiality of the
              Account and information thereto and are fully responsible for all
              activities that occur under your Account. The transaction and
              delivery of the Products or availing the Services may also be
              subject to procedures for use of the Platform, Terms, uploaded
              guidelines, rules, additional terms of service, or other
              disclaimer & notices, if any (Additional Terms). If there is any
              conflict between the Terms and the Additional Terms, the
              Additional Terms shall take precedence in relation to that
              service.{" "}
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(e).</span>
            <p>
              We cannot and will not be liable for any loss or damage arising
              from your failure to comply with this Paragraph 4. You may be held
              liable for losses incurred by us or any other user of or visitor
              to the Platform due to authorized or unauthorized use of your
              Account as a result of your failure in keeping your Account
              Information secure and confidential or otherwise. The Platform
              also allows / shall allow restricted access to the Platform for
              unregistered Users. Use of another users Account for availing the
              Services or Products is expressly prohibited. If you provide any
              information that is untrue, inaccurate, not current or incomplete
              (or becomes untrue, inaccurate, not current or incomplete), or we
              have reasonable grounds to suspect that such information is
              untrue, inaccurate, not current or incomplete, we reserve the
              right to suspend or terminate Your Account and refuse any and all
              current or future use of the Platform by you.{" "}
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(f).</span>
            <p>
              You confirm that you are the authorised holder of the credit card,
              any payment instrument, or the original Account holder used in the
              transactions he/she makes using the Platform. We will not be
              responsible for any financial loss, inconvenience or mental agony
              resulting from misuse of your ID/password/credit card
              number/Account details for using the Platform.
            </p>
          </div>
          <br />
          <div className="flex ">
            <strong className="pr-4">5.</strong>
            <p className="font-bold">PAYMENT TERMS</p>
            <br />
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(a).</span>
            <p>
              Accuracy: Subject to applicable laws, prices are subject to change
              by us without notice to you. We strive to provide accurate product
              and price information; however, pricing errors may occur from time
              to time.{" "}
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>
            <p>
              Full Price: Unless otherwise stated at the time of checkout, you
              agree to pay the full price of the Product and/or the Services.
              Offers and discounts will be offered at our sole discretion. We
              reserve the right to refuse or cancel applications of offers and
              discounts for your order.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(c).</span>
            <p>
              Wrong Pricing: We cannot confirm the price of the Product and/or
              the Service until you place an order. If a Product/Service is
              listed at an incorrect price or with incorrect information due to
              any technical error, we shall have the right, at our sole
              discretion, to refuse or cancel any orders placed for that
              Product/Service, unless the Product/Service has already been
              delivered. In the event that an item is wrongly priced, we may, at
              our discretion, either contact you for instructions or cancel your
              order and notify you of such cancellation. Products in your
              shopping cart of the Platform will reflect the most recent price
              as displayed on the Product’s information page on the Platform.
              Please note that this price may differ from the price shown for
              the Product when you first placed it in your shopping cart.
              Placing a Product in your shopping cart does not reserve the price
              shown at that time. It is also possible that a Product’s price may
              vary between the time you place it in your shopping cart and the
              time you place the order. The price as applicable at the time of
              placing order shall be final.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(d).</span>
            <p>
              Returns/Cancellation: Your eligibility for returns/cancellation
              will be in accordance with our returns, refund and cancellation
              policy.(d) Returns/Cancellation: Your eligibility for
              returns/cancellation will be in accordance with our returns,
              refund and cancellation policy.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(e).</span>
            <p>
              Taxes: The prices/fee are exclusive of applicable taxes. These
              shall be added to your invoice at checkout as applicable. Each
              User / third party service provider is solely responsible for
              payment of all taxes, legal compliances, statutory registrations
              and reporting. We shall in no way be responsible for any of the
              taxes except for our own taxes.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(f).</span>
            <p>
              Shipping or any other additional charges: Shipping or any other
              additional charges (if applicable) are automatically added to your
              invoice as per standard rates and shall be displayed on the
              Platform.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(g).</span>
            <p>Further:</p>
          </div>
          <br />
          <ul className="list-disc pl-16">
            <li>
              All commercial terms such as price, delivery, dispatch of Products
              and/or services are as per principal-to-principal bipartite
              contractual obligations between you and us.
            </li>
            <li>Refund shall be subject to user complying with these Terms.</li>
            <li>
              We reserve the right to refuse to process orders/requisitions from
              users with a prior history of questionable charges including
              without limitation breach of any agreements by user with us or
              breach of any policy.
            </li>
            <li>
              You acknowledge that there may be licenses/permissions required
              under the applicable laws to use, purchase or otherwise possess
              certain Product(s) by you. You will be solely responsible for
              obtaining such licenses/permissions and complying with the terms
              of such licenses/permissions.
            </li>
            <li>
              Security Measures- The payment made for every transaction is done
              through API integration. Moreover, you may also check our Privacy
              Policy to understand how we use the confidential information
              provided by you.
            </li>
            <li>
              Dispute- Any dispute in connection to the third-parties services
              shall be settled between the Users and the respective third
              parties, including without limitations, banks/payment
              gateways/payment aggregators/network operators without involving
              us.
            </li>
          </ul>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(h).</span>
            <p>
              Payment Processor: In order to process the payments for your
              orders, we may require details of your bank account, credit card
              number, etc. The online fee payments made by You are processed
              with the support and services of the banks/payment
              gateways/payment aggregators/ third parties and we are not
              responsible for any loss or damage caused to you/ third party
              service providers during this process as these banks/payment
              gateways/payment aggregators/ third parties are beyond our
              control. We use a third-party payment processor (“Payment
              Processor”) to bill you through your selected mode of payment. The
              processing of payments will be subject to the terms and policies
              of such Payment Processors in addition to these Terms. We shall
              not be liable for any error by the Payment Processor. In the event
              of any unsuccessful payments, the money so debited shall be
              credited in accordance with the terms of the Payment Processor.
            </p>
          </div>
          <br />
          <div className="flex ">
            <strong className="pr-4">6.</strong>
            <p className="font-bold">THIRD PARTY SERVICES</p>
            <br />
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(a).</span>
            <p>
              The Services may include services, content, documents, and
              information owned by, licensed to, or otherwise made available by
              a third party (“Third Party Services”) or contain links to Third
              Party Services. You understand that Third Party Services are the
              responsibility of the third party that created or provided it and
              acknowledge that use of such Third Party Services is solely at
              their own risk.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>
            <p>
              We make no representations and excludes all warranties and
              liabilities arising out of or pertaining to such Third Party
              Services, including their accuracy or completeness. Further, all
              intellectual property rights in and to Third Party Services are
              the property of the respective third parties.
            </p>
          </div>
          <br />
          <div className="flex ">
            <strong className="pr-4">7.</strong>
            <p className="font-bold">YOUR RESPONSIBILITIES</p>
            <br />
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(a).</span>
            <p>
              You represent and warrant that all information that is provided
              on/through the Platform or in relation to the Services is
              complete, true, and correct on the date of agreeing to these Terms
              and shall continue to be complete, true, and correct while you
              avail the Services or the Products. Should any information that
              you provide change during the existence of these Terms, you
              undertake to immediately bring such change to our notice. We do
              not accept any responsibility or liability for any loss or damage
              that you may suffer or incur if any information, documentation,
              material, or data provided to avail the Services is incorrect,
              incomplete, inaccurate, untrue, or misleading, or if you fail to
              disclose any material fact.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>
            <p>
              You shall be solely responsible for ensuring compliance with
              applicable laws and shall be solely liable for any liability that
              may arise due to a breach of its obligations in this regard.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(c).</span>
            <p>
              You shall extend all cooperation to us in its defence of any
              proceedings that may be initiated against it due to a breach of
              your obligations or covenants under these Terms.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(d).</span>
            <p>
              You shall not use the Platform or avail, the Services/Products in
              any manner except as expressly permitted in these Terms. Without
              limiting the generality of the preceding sentence, you may not:
            </p>
          </div>
          <br />
          <div className="flex pl-12">
            <span className="pr-4">(i).</span>
            <p>
              infringe any proprietary rights, including but not limited to
              copyrights, patents, trademarks, or trade secrets, of any party;
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-4">(ii).</span>
            <p>
              except as may be provided hereunder, copy, display, distribute,
              modify, publish, reproduce, duplicate, sell, resell, store,
              transmit, post, translate, create any derivative works from, or
              license the Services;
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-4">(iii).</span>
            <p>
              use the Services to transmit any data or send or upload any
              material that contains viruses, Trojan horses, worms, timebombs,
              keystroke loggers, spyware, adware, or any other harmful
              programmes or similar computer code designed to adversely affect
              the operation of any computer software or hardware;
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-4">(iv).</span>
            <p>
              use any robot, spider, other automated device, or manual process
              to monitor or copy the Platform or Services or any portion
              thereof;
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-4">(v).</span>
            <p>
              engage in the systematic retrieval of content from the Platform or
              the Services to create or compile, directly or indirectly, a
              collection, compilation, database, or directory;
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-4">(vi).</span>
            <p>
              harass, abuse, insult, harm, defame, slander, disparage,
              intimidate, or discriminate based on gender, sexual orientation,
              religion, ethnicity, race, age, national origin, or disability;
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-4">(vii).</span>
            <p>
              upload or transmit any information or content that is obscene,
              pornographic, paedophilic, immoral, invasive of another’s privacy,
              or is relating or encouraging money laundering or gambling, an
              online game that causes user harm, or promoting enmity between
              different groups on the grounds of religion or caste with the
              intent to incite violence;
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-4">(viii).</span>
            <p>
              act in an abusive or threatening manner or use abusive or
              threatening language on or through the Platform;
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-4">(ix).</span>
            <p>
              upload or transmit information or content that is harmful to
              children or that impersonates another person, or deceive or
              mislead any addressee about the origin of a message or knowingly
              and intentionally communicates any misinformation or information
              which is patently false and untrue or misleading in nature or, in
              respect of any business of the Indian government, is identified as
              fake or false or misleading by the fact check unit of the Indian
              government;
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-4">(x).</span>
            <p>
              threaten the unity, integrity, defence, security or sovereignty of
              India, friendly relations with foreign states, or public order, or
              cause incitement to the commission of any cognizable offence, or
              prevent investigation of any offence, or insult another nation in
              any manner;
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-4">(xi).</span>
            <p>
              upload or transmit any information or content in the nature of an
              online game that is not verified as a permissible online game
              under Indian laws or is in the nature of advertisement or
              surrogate advertisement or promotion of an online game that is not
              a permissible online game, or of any online gaming intermediary
              offering such an online game;
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-4">(xii)</span>
            <p>
              use the Services in (A) any unlawful manner, (B) for fraudulent or
              malicious activities, or (C) in any manner inconsistent with these
              Terms; or
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-4">(xiii)</span>
            <p>
              violate applicable laws or solicit others to violate applicable
              laws in any manner.
            </p>
          </div>
          <br />
          <div className="flex ">
            <strong className="pr-4">8.</strong>
            <p className="font-bold">INTELLECTUAL PROPERTY RIGHTS</p>
            <br />
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(a).</span>
            <p>
              All information, content, material, text, graphics, images, logos,
              button icons, software code, interface, design and the collection,
              arrangement and assembly of the content on the Platform are our
              property or our affiliates (“Company Content”), and are protected
              under copyright, trademark and other applicable laws.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>
            <p>
              The trademarks, logos and service marks displayed on the Platform
              (Marks) are our property or our third party partners or respective
              third parties. You are not permitted to use the Marks without our
              prior consent and/or the relevant third parties that may own the
              Marks. Unless otherwise indicated or anything contained to the
              contrary or any proprietary material owned by a third party and so
              expressly mentioned, We own all intellectual property rights in
              and to the trademark “MoolHealth”, domain names, and the Platform,
              including, without limitation, any and all rights, title and
              interest in and to copyright, related rights, patents, utility
              models, designs, know-how, trade secrets and inventions (patent
              pending), goodwill, source code, meta tags, databases, text,
              content, graphics, icons, and hyperlinks.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(c).</span>
            <p>
              All Product names, whether or not appearing with the trademark
              symbol, are trademarks that belong to us unless otherwise stated
              by us. The use or misuse of these trademarks or any other
              materials, except as permitted in these Terms, is expressly
              prohibited and may be in violation of copyright law, trademark
              law, and any other applicable law.{" "}
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(d).</span>
            <p>
              The contents of this Platform are subject to copyright protection.
              The contents of the Platform may not be copied, recopied,
              reproduced, or otherwise redistributed. You should not copy,
              display, download, distribute, modify, reproduce, republish or
              retransmit any information, text or documents contained in this
              Platform or any portion thereof in any electronic medium or in
              hard copy, or create any derivative work based on such images,
              text or documents, without our express written consent or as
              otherwise permitted in these Terms.{" "}
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(e).</span>
            <p>
              We may request you to submit suggestions and other feedback,
              including bug reports, relating to the Products or Services from
              time to time (“Feedback”). Wemay freely use, copy, disclose,
              publish, display, distribute, and exploit the Feedback without any
              payment of royalty, acknowledgement, prior consent, or any other
              form of restriction arising out of your intellectual property
              rights. You hereby waive any rights you may have that arise out of
              such Feedback and agree to execute such documentation as We may
              request to give effect to our rights under this clause.{" "}
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(f).</span>
            <p>
              You may upload or submit certain information, content,
              submissions, ideas, suggestions, proposals, plans, or other
              material, whether with or without our request (collectively,
              “Content”). You hereby grant us a non-exclusive, worldwide,
              perpetual, irrevocable, transferable, sublicensable, and
              royalty-free license to use, display, store, host, communicate,
              make available, modify, adapt, translate, and create derivative
              works of the Content (i) for the functioning of and in connection
              with the Platform, the Services, or the Products; and (ii) in
              order to facilitate tele consultation with the healthcare
              professionals and share information with them and our
              representatives.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(g).</span>
            <p>
              Your use of the Platform, the Services, and access to the Company
              Content is subject to a limited, revocable and non-exclusive
              license which is granted to you when you register on the Platform.
              You will use the Platform solely for availing Services,
              identifying Products, carrying out purchases of Products and
              processing returns and refunds, for your personal use only and not
              for business purposes.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(h).</span>
            <p>
              The license granted to you does not include a license for: (a)
              resale of Products or commercial use of the Platform or the
              Company Content, (b) any collection and use of product listings,
              description, or prices, (c) any use of the Platform, the Services
              and/or of the Company Content other than as contemplated in these
              Terms, (d) any downloading or copying of Account Information, (e)
              any use of data mining, robots, or similar data gathering and
              extraction tools to extract (whether once or many times) any parts
              of the Platform, (e) creating and/ or publishing your own database
              that features parts of the Platform.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(i).</span>
            <p>
              Except as stated in these Terms, nothing in these Terms should be
              construed as conferring any right in or licence to our or any
              third party’s intellectual rights.
            </p>
          </div>
          <br />
          <div className="flex ">
            <strong className="pr-4">9.</strong>
            <p className="font-bold">TERM AND TERMINATION</p>
            <br />
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(a).</span>
            <p>
              These Terms shall remain in effect unless terminated in accordance
              with the terms hereunder.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>
            <p>
              We may terminate your access to or use of the Services, or any
              portion thereof, immediately and at any point, at its sole
              discretion if you violate or breach any of its obligations,
              responsibilities, or covenants under these Terms.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(c).</span>
            <p>Upon termination under Clause 8(b):</p>
          </div>
          <br />
          <div className="flex pl-16">
            <span className="pr-4">(i).</span>
            <p>the Services will “time-out”;</p>
          </div>
          <div className="flex pl-16">
            <span className="pr-4">(ii).</span>
            <p>
              you shall not be eligible to avail any features of the Services or
              purchase the Products; and
            </p>
          </div>
          <div className="flex pl-16">
            <span className="pr-4">(iii).</span>
            <p>
              these Terms shall terminate, except for those clauses that
              expressly or are intended to survive termination or expiry.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(d).</span>
            <p>
              Notwithstanding anything to the contrary contained in the Terms,
              upon termination of your access to or use of the Services, all
              amounts, or outstanding monies due by you in relation to your use
              of or access to the Services, or purchase of the Products shall
              become immediately payable.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(e).</span>
            <p>
              All other rights accrued before the termination shall continue to
              remain valid after such termination and clauses which by their
              nature survive such termination shall continue to remain valid and
              binding.
            </p>
          </div>
          <br />
          <div className="flex ">
            <strong className="pr-4">10.</strong>
            <p className="font-bold">
              DISCLAIMERS OF WARRANTIES AND LIABILITIES
            </p>
            <br />
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(a).</span>
            <p>use of the Services or the Products is at your sole risk.</p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>
            <p>
              To the extent permitted by applicable law, the Services are
              provided on an “as is” and “as available” basis. We do not warrant
              that operation of the Platform or availability of the Services
              will be uninterrupted or error free or that the functions
              contained in the Services will meet your requirements. Without
              limiting the foregoing, We do not make any warranty that (i) the
              Platform or the Services will meet your requirements; (ii) the
              results that may be obtained from the use of the Platform,
              Services or materials will be effective, accurate or reliable;
              (iii) the quality of the Platform, Services or other materials
              will meet your expectations; or that (iv) any errors or defects in
              the Platform, Services or other materials will be corrected. No
              advice or information, whether oral or written, obtained by you
              from us or through or from use of the Services shall create any
              warranty not expressly stated in the Terms.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(c).</span>
            <p>
              To the maximum extent permitted by applicable law, We will have no
              liability related to user content arising under intellectual
              property rights, libel, privacy, publicity, obscenity or other
              laws. We also disclaim all liability with respect to the misuse,
              loss, modification or unavailability of any user content.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(d).</span>
            <p>
              We have endeavoured to ensure that all the information on the
              Platform is correct, but we neither warrant nor make any
              representations regarding the quality, accuracy or completeness of
              any data, information, product or service. We shall not be
              responsible for the delay or inability to use the Platform or
              related functionalities, the provision of or failure to provide
              functionalities, or for any information, software, products,
              functionalities and related graphics obtained through the
              Platform, or otherwise arising out of the use of the Platform,
              whether based on contract, tort, negligence, strict liability or
              otherwise. Further, We shall not be held responsible for
              non-availability of the Platform during periodic maintenance
              operations or any unplanned suspension of access to the Platform
              that may occur due to technical reasons or for any reason beyond
              our control. The user understands and agrees that any material or
              data downloaded or otherwise obtained through the Platform, is
              done entirely at their own discretion and risk and they will be
              solely responsible for any damage to their computer systems or
              loss of data that results from the download of such material or
              data. We are not responsible for any typographical error leading
              to an invalid coupon. We accept no liability for any errors or
              omissions, with respect to any information provided to you whether
              on behalf of itself or third parties.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(e).</span>
            <p>
              To the fullest extent permissible under applicable law, We
              expressly disclaim all warranties of any kind, express or implied,
              arising out of the Services and the Products, including warranties
              of merchantability, fitness for a particular purpose, satisfactory
              quality, accuracy, title and non-infringement, compatibility,
              applicability, usability, appropriateness, and any warranty that
              may arise out of course of performance, course of dealing, or
              usage of trade
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(a).</span>
            <p>
              You hereby accept full responsibility for any consequences that
              may arise from your use of the Services or the Products, and
              expressly agree and acknowledge that We shall have absolutely no
              liability with respect to the same.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>
            <p>
              To the fullest extent permissible by law, We, our affiliates, and
              our related parties each disclaim all liability to you for any
              loss or damage arising out of or due to:
            </p>
          </div>
          <br />
          <div className="flex pl-12">
            <span className="pr-6">(i).</span>
            <p>
              your use of, inability to use, or availability or unavailability
              of the Services, including any Third Party Services;
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-6">(ii).</span>
            <p>
              the occurrence or existence of any defect, interruption, or delays
              in the operation or transmission of information to, from, or
              through the Services, communications failure, theft, destruction,
              or unauthorised access to our records, programmes, services,
              server, or other infrastructure relating to the Services.
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-6">(iii).</span>
            <p>
              the failure of the Services to remain operational for any period
              of time; or
            </p>
          </div>
          <div className="flex pl-12">
            <span className="pr-6">(iv).</span>
            <p>
              the collection or processing of your personal information by us.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(c).</span>
            <p>
              Notwithstanding anything to the contrary contained herein, neither
              us nor any of our affiliates or related parties shall have any
              liability to you or any third party for any indirect, incidental,
              special, or consequential damages or any loss of revenue or
              profits arising under, directly, or indirectly, or relating, in
              any manner whatsoever, in relation to the use of the Platform,
              these Terms or the Services. To the maximum extent permitted by
              law, you agree to waive, release, discharge, and hold us harmless
              , our affiliated and subsidiary companies, our parent companies,
              and each of our directors, officers, employees, and agents, from
              any and all claims, losses, damages, liabilities, expenses and
              causes of action arising out of use of the Platform or the
              Services.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(d).</span>
            <p>
              We are not liable if your access or use of the Platform or the
              Services is affected by incompatible hardware or an insecure
              internet connection.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(e).</span>
            <p>
              You understand that your data may be transferred unencrypted and
              involve (i) transmissions over various networks; and (ii) changes
              to conform and adapt to technical requirements of connecting
              networks or devices.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(f).</span>
            <p>
              You understand that the material on this Platform is provided for
              general information only and should not be relied upon or used as
              the sole basis for making decisions without consulting primary,
              more accurate, more complete, or more timely sources of
              information. Any reliance on the material on the Platform is at
              your own risk.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(g).</span>
            <p>
              You acknowledge and agree that MoolHealth is a mere technology
              platform and is not engaged in the provision of medical or
              healthcare services.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(h).</span>
            <p>
              WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, WE DO NOT
              RECOMMEND OR ENDORSE ANY SPECIFIC DRUGS, TESTS, PHYSICIANS,
              PRODUCTS, PROCEDURES, OPINIONS, “OFF-LABEL” DRUG USES, OR ANY
              OTHER INFORMATION THAT MAY BE PROVIDED THROUGH THE PLATFORM. ANY
              CONTENT AVAILABLE ON THE PLATFORM IS FOR GENERAL INFORMATION
              PURPOSES ONLY AND DOES NOT CONSTITUTE EITHER AN ADVERTISEMENT OR
              PROMOTION OF ANY DRUG BEING OFFERED FOR SALE OR ANY PROFESSIONAL
              MEDICAL ADVICE, DIAGNOSIS, TREATMENT OR RECOMMENDATION OF ANY
              KIND. YOU ARE RESPONSIBLE FOR CONDUCTING YOUR OWN DUE DILIGENCE,
              INVESTIGATION, VALUATION, AND EVALUATION OF THE SERVICES INCLUDING
              ANY PRODUCTS AVAILABLE THROUGH THE SERVICES.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(i).</span>
            <p>
              We provide the Services and the Products in compliance with laws
              applicable in India. We are not responsible for any differences
              between such rules and any different rules applying to healthcare
              services in any country other than India. If you are accessing or
              using the Services or the Products outside the territory of India,
              it is your sole responsibility to ensure whether it is lawful to
              access the Services or the Products in the territory where you are
              located. We shall have no liability in this regard.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(j).</span>
            <p>
              We shall have no liability to you if we are prevented from or
              delayed in performing our obligations or from carrying on our
              business, by acts, events, omissions or accidents beyond our
              control, including, without limitation, strikes, lock-outs or
              other industrial disputes (whether involving our workforce or any
              other party), failure of a utility service or telecommunications
              network, act of God, war, riot, civil commotion, malicious damage,
              compliance with any law or governmental order, rule, regulation or
              direction, accident, breakdown of machinery, fire, flood, storm or
              default of suppliers or sub-contractors.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(k).</span>
            <p>
              The healthcare professionals will not be examining you physically
              and may not have access to all or some of your medical history
              that might be critical to consult you. The healthcare
              professionals will not have the benefit of information that would
              be obtained by examining you in person, observing your physical
              condition and by going through your medical records. This means
              that the Services provided is different from the diagnostic and
              treatment services typically decided by a physician examining you
              physically. Therefore, the healthcare professionals may not be
              aware of facts or information that would affect his or her opinion
              of your diagnosis. You acknowledge and agree, by requesting a
              consultation through the Platform, that-
            </p>
          </div>
          <ul className="list-disc pl-16">
            <li>
              the advice/information/opinion on diagnosis you may receive could
              be limited and provisional;
            </li>
            <li>
              in case of a second opinion, where there is a difference of
              opinion between the healthcare professional, you would bear the
              responsibility to decide on online or offline consultation, or
              procedure, and/or treatment;
            </li>
            <li>
              there are inherent differences between a physical consultation and
              tele-consultation and thus there is a dependency/reliability on
              the Information provided by you and hence any such Information
              that is false, misleading, inaccurate, outdated or incomplete will
              immediately render the opinion, consultation, test results, and
              all details therein null and void;
            </li>
            <li>
              in some events, the healthcare professionals may determine that
              the transmitted information is of inadequate quality and may ask
              for more information, without which he/she may refuse to answer
              the query;
            </li>
            <li>
              in rare cases, the healthcare professionals may feel that the
              query may not be answerable without physically examining the
              patient/ Users and the consultation may be refused forthwith;
            </li>
            <li>
              in very rare instances, security protocols could fail, causing a
              breach of privacy of personal medical information; and
            </li>
            <li>
              delays in medical evaluation and answers could occur due to
              deficiencies or failures of the service as per those mentioned in
              these Terms.
            </li>
          </ul>
          <br />
          <div className="flex ">
            <strong className="pr-4">11.</strong>
            <p className="font-bold">NOTICE AND TAKEDOWN</p>
            <br />
          </div>
          <br />
          <p className="pl-6">
            If you believe that any Content on the Platform is defamatory,
            obscene, pornographic, paedophilic, illegal, offensive, sexually
            explicit, promotes bigotry, hatred or physical harm, deceptive,
            misleading, abusive, indecent, harassing, blasphemous, defamatory,
            libellous, invasive of another’s privacy, including bodily privacy,
            insulting or harassing on the basis of gender, racially or
            ethnically objectionable, relating or encouraging money laundering
            or gambling; or is otherwise injurious to third parties; or is
            harmful to minors in any way; or impersonates another person; or
            threatens the unity, integrity, security or sovereignty of any
            nation or its or friendly relations with foreign states; or which
            consists of or contains software viruses or violates any of the
            Terms, please notify us immediately at the contact information
            provided below. As soon as you inform us, we will make all
            reasonable endeavours to remove such objectionable content
            complained about within a reasonable time.
          </p>
          <br />
          <div className="flex ">
            <strong className="pr-4">12.</strong>
            <p className="font-bold">INDEMNITY AND LIMITATION OF LIABILITY</p>
            <br />
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(a).</span>
            <p>
              You shall indemnify, defend at our option, and hold us, our parent
              companies, subsidiaries, affiliates, and our officers, associates
              successors, assigns, licensors, employees, directors, agents, and
              representatives, harmless from and against any claim, demand,
              lawsuits, judicial proceeding, losses, liabilities, damages and
              costs (including, without limitation, from all damages,
              liabilities, settlements, costs and attorneysʼ fees) due to or
              arising out of your access to the Services, availment/ use of the
              Services, use of the Products, violation of these Terms, violation
              of applicable laws, or any violation by any third party who may
              use your Account, of these Terms.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>
            <p>
              Notwithstanding anything to the contrary, in no event, our
              aggregate liability, shall extend beyond the money charged from
              you for purchases made pursuant to an order under which such
              liability has arisen and been established. We will not be
              responsible for any business loss (including loss of profits,
              revenue, contracts, anticipated savings, data, goodwill or wasted
              expenditure) or any other indirect or consequential loss that is
              not reasonably foreseeable to both you and us when a contract for
              the sale of Product by us to you was formed.
            </p>
          </div>
          <br />
          <div className="flex ">
            <strong className="pr-4">13.</strong>
            <p className="font-bold">CONSENT TO USE DATA</p>
            <br />
          </div>
          <br />
          <p className="pl-6">
            You agree that We may, in accordance with its our Privacy Policy
            collect and use the information provided by you.
          </p>
          <br />
          <div className="flex ">
            <strong className="pr-4">14.</strong>
            <p className="font-bold">MODIFICATION OF SERVICES AND PRODUCTS</p>
            <br />
          </div>
          <br />
          <p className="pl-6">
            We reserve the right at any time to add, modify or discontinue,
            temporarily or permanently, the Services (or any part thereof) or
            any and all of the Products with or without cause. We shall not be
            liable for any such addition, modification, suspension, or
            discontinuation of the Services or the Products.
          </p>
          <br />
          <div className="flex ">
            <strong className="pr-4">15.</strong>
            <p className="font-bold">
              GOVERNING LAW, JURISDICTION, AND DISPUTE RESOLUTION
            </p>
            <br />
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(a).</span>
            <p>
              These Terms shall be governed by and construed and enforced in
              accordance with the laws of India. Subject to other provisions in
              this Clause, courts in Mumbai, India shall have exclusive
              jurisdiction over all issues arising out of these Terms or the use
              of the Services.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>
            <p>
              Any controversies, conflicts, disputes, or differences arising out
              of these Terms shall be resolved by arbitration in Ahmedabad in
              accordance with the Arbitration and Conciliation Act, 1996 for the
              time being in force, which is deemed to be incorporated by
              reference in this Clause. The tribunal shall consist of 1 (One)
              arbitrator appointed by us. The language of the arbitration shall
              be English.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(c).</span>
            <p>
              The parties to the arbitration shall keep the arbitration
              confidential and not disclose to any person, other than on a need
              to basis or to legal advisors, unless required to do so by law.
              The decision of the arbitrator shall be final and binding on all
              the Parties hereto.
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(d).</span>
            <p>
              Each party to the arbitration shall bear its own costs with
              respect to any dispute.
            </p>
          </div>
          <br />

          <div className="flex ">
            <strong className="pr-4">16.</strong>
            <p className="font-bold">MISCELLANEOUS</p>
            <br />
          </div>
          <br />

          <div className="flex pl-4">
            <span className="pr-4">(a).</span>
            <p>
              (a) Grievance Redressal: You may contact us by writing to our
              Grievance Officer/Customer Care at the address provided below:{" "}
              <br />
              <br />
              Name: Sulakshana Sarathy <br />
              Address: Tatvartha Health Private Limited, 1st Floor, Interface 16 Rd, Malad, Mindspace, Malad West,
              Mumbai, Maharashtra 400064 <br />
              Email Address: support@vayu.com
            </p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(b).</span>
            <p>Modification: We reserve the right at any time to modify these Terms and to add new or additional terms or conditions on use of the Platform or availment of the Services or Products. Such modifications and additional terms and conditions will be communicated to you and, unless expressly rejected (in which these Terms shall terminate), will be effective immediately and will be incorporated into these Terms. In the event you refuse to accept such changes, these Terms will terminate.</p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(c).</span>
            <p>Severability: If any provision of these Terms is determined by any court or other competent authority to be unlawful or unenforceable, the other provisions of these Terms will continue in effect. If any unlawful or unenforceable provision would be lawful or enforceable if part of it were deleted, that part will be deemed to be deleted, and the rest of the provision will continue in effect (unless that would contradict the clear intention of the clause, in which case the entirety of the relevant provision will be deemed to be deleted).</p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(d).</span>
            <p>Assignment: You shall not licence, sell, transfer or assign your rights, obligations, or covenants under these Terms in any manner without our prior written consent. We may grant or withhold this consent in its sole discretion and subject to any conditions it deems appropriate. We may assign its rights to any of its affiliates, subsidiaries, or parent companies, or to any successor in interest of any business associated with the Services without any prior notice to you.</p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(e).</span>
            <p>Notices: All notices, requests, demands, and determinations for us under these Terms (other than routine operational communications) shall be sent to support@vayu.com  .</p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(f).</span>
            <p>Third-Party Rights: No third party shall have any rights to enforce any terms contained herein.</p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(g).</span>
            <p>Waiver: Any failure by us to enforce or exercise any provision of the Terms, or any related right, shall not constitute a waiver by us of that provision or right</p>
          </div>
          <br />
          <div className="flex pl-4">
            <span className="pr-4">(h).</span>
            <p>Force Majeure: We will not be held responsible for any delay or failure to comply with our obligations if the delay or failure arises from any cause which is beyond our reasonable control.</p>
          </div>
          <br />
        </div>
      </div>
    </div>
  );
};

export default TermsConditionsPage;
